name: CI

on: [push, pull_request]

# clear all permissions for GITHUB_TOKEN
permissions: {}

jobs:
  build:
    # execute on any push or pull request from forked repo
    if: github.event_name == 'push' || ( github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork )

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        maven: [ '3.8.6', '3.8.7', '4.0.0-alpha-3' ]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Java/Maven
        uses: s4u/setup-maven-action@v1.6.0
        with:
          cache-prefix: 'cache-'
          java-version: 8
          java-distribution: 'zulu'
          maven-version: ${{ matrix.maven }}

#      - name: Set up Maven
#        uses: stCarolas/setup-maven@v4.5
#        with:
#          maven-version: 3.8.6
#
#      - name: Set up Java 8
#        uses: actions/setup-java@v3
#        with:
#          java-version: 8
#          distribution: 'zulu'
#
#      - name: Cache save/restore
#        uses: actions/cache@v3
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn verify --errors --batch-mode --show-version

  gh-pages-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Prepare Maven local Repository
        run: ${PWD}/bin/prepare-local-repo.sh

      - name: Generate site staging
        run: ${PWD}/bin/gh-pages-create.sh

      - name: List files in target/gh-pages
        run: ls -lR ${JAVA_HOME}/jre/lib
